### ISSUE TITLE
Homemade horn antenna

### ISSUE THREAD

**Issue by AlexBdx** [matthuszagh/fmcw-radar#9]
I remember you previously said you wanted to make your own antenna.
I found this article: https://antennatestlab.com/3dprinting
and made my own horn antennas for the fmcw3. They cost nothing and are fun to build.

**Comment by AlexBdx** [comment]
Purely informational. If you do not have a 3d printer available and want one you can email me.

**Comment by matthuszagh** [comment]
This is awesome, thank you for sharing! I do have a 3D printer, but thank you for offering.

**Comment by matthuszagh** [comment]
I'm curious, did you build small horn antennas for reception too, or just a large one for transmission?

**Comment by AlexBdx** [comment]
If I just want the range-time plot, I use two horns like Henrik does (check out his new article if you have not already).
If I want the angle plots, I use the horn for the transmission only due to the need to have a specific alignment between the receiver antennas.
That being said, you could probably design a narrow lambda/2 horn, and stack a bunch side by side with a lambda/2 pitch. The horn would be non-ideal, but it might be better than the FR4 patch \o/

**Comment by matthuszagh** [comment]
Yeah I'm not in love with the patches. The bandwidth on them is terrible and FR4 is tough to work with for antennas. I'll see if I can make horns small enough for reception and report back if they work any better.

**Comment by AlexBdx** [comment]
Sounds good.

**Comment by matthuszagh** [comment]
you used the wr187? what did you do for waveguide coax adapters?

**Comment by matthuszagh** [comment]
wr159 is a better frequency range but i don't see an stl model for it

**Comment by AlexBdx** [comment]
No I made a WR-159

**Comment by matthuszagh** [comment]
is the model there and i missed it or you made it yourself?

**Comment by AlexBdx** [comment]
I made a CAD myself for the WR-159 and 3d printed it. I used the following drawing: https://www.pasternack.com/images/ProductPDF/PE9860-15.pdf
My 3D printer can only do 6"x6"x6" so I had to split it in 2. I did not have the motivation to split it in 4 to make a 20 dBi version

**Comment by AlexBdx** [comment]
Let me see if I can 1) find the file 2) attach it on Github

**Comment by AlexBdx** [comment]
> 
> 
> you used the wr187? what did you do for waveguide coax adapters?

2nd part of the answer: I *could* have 3D printed one, but I concluded it would be too risky. So I just bought this: https://www.ebay.com/itm/232688038314
I'm already saving $1000+ so I just spent the $50 for the adapter.

**Comment by matthuszagh** [comment]
makes sense, thanks

**Comment by AlexBdx** [comment]
**EDITED**
[WR-159_15_dBi.zip](https://github.com/matthuszagh/fmcw-radar/files/3572614/WR-159_15_dBi.zip)
Assembly_15_dBi is for reference. 
There are two main parts due to the size constraints of my printer. Support_PLA is a conical section that holds the top and bottom parts aligned while you weld them together (via solvent, glue or else)

**Comment by matthuszagh** [comment]
thanks!
